# Generated by Django 4.1.6 on 2023-02-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cat_imgs/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(default=models.CharField(max_length=200), max_length=400)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded/')),
                ('type', models.CharField(choices=[('R', 'Rent'), ('S', 'For Sale'), ('L', 'For Lease')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_house_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
            ],
            options={
                'verbose_name_plural': '2. Listings',
            },
        ),
    ]
