# Generated by Django 4.1.6 on 2023-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_house_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
