# Generated by Django 4.1.6 on 2023-02-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='num_bathrooms',
            new_name='number_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='num_bedrooms',
            new_name='number_of_bedrooms',
        ),
    ]
