# Generated by Django 4.1.6 on 2023-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_category_options_remove_listing_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_footage',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
