# Generated by Django 4.1.6 on 2023-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_price_alter_listing_square_footage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='payment_type',
            field=models.CharField(choices=[(1, 'Rent'), (2, 'For Sale')], max_length=150),
        ),
    ]
