# Generated by Django 4.1.6 on 2023-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='payment_type',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'For Sale')], max_length=1),
        ),
    ]
