# Generated by Django 4.1.6 on 2023-03-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
