# Generated by Django 4.1.6 on 2023-02-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='vendor',
            new_name='Agent',
        ),
    ]
