# Generated by Django 4.1.6 on 2023-03-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_type_listing_tenancy_listing_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tenancy',
            new_name='type',
        ),
    ]
