# Generated by Django 4.1.6 on 2023-02-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_vendor_listing_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='square_footage',
            new_name='area_sqft',
        ),
    ]
