# Generated by Django 4.1.6 on 2023-02-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_square_footage_listing_area_sqft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='payment_type',
            new_name='type',
        ),
    ]
