# Generated by Django 4.1.6 on 2023-02-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
