# Generated by Django 4.1.6 on 2023-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_pinterest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
