# Generated by Django 4.1.6 on 2023-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_tiktok_url_profile_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '3. Agents'},
        ),
    ]
